openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: 'https://api.example.com/v1'

paths:
  /items:
    get:
      summary: Get a list of items
      operationId: getItems
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Create a new item
      operationId: postItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: The created item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /items/{itemId}:
    parameters:
      - name: itemId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get an item by ID
      operationId: getItem
      responses:
        '200':
          description: The requested item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    put:
      summary: Update an item by ID
      operationId: putItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: The updated item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    patch:
      summary: Partially update an item by ID
      operationId: patchItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: The partially updated item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    delete:
      summary: Delete an item by ID
      operationId: deleteItem
      responses:
        '204':
          description: The item was deleted successfully
    options:
      summary: Retrieve the allowed methods for an item
      operationId: optionsItem
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The allowed methods
          headers:
            Allow:
              schema:
                type: string
                example: 'GET, PUT, PATCH, DELETE, OPTIONS'

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the item
        name:
          type: string
          description: The name of the item
        description:
          type: string
          description: A brief description of the item
        price:
          type: number
          format: float
          description: The price of the item
